
import { Question, QuestionType } from '../types';
import { hawaiiQuestions } from './hawaiiQuestions';

const baseQuestions: Question[] = [
  // Contact Information
  { id: 'q1', section: 'Contact Information', text: 'Name or Representative for {Destination}:', type: QuestionType.TEXT },
  { id: 'q2', section: 'Contact Information', text: 'Please enter contact email for {Destination}:', type: QuestionType.EMAIL },
  { id: 'q3', section: 'Contact Information', text: 'Please enter contact phone for {Destination}:', type: QuestionType.TEL },
  { id: 'q4', section: 'Contact Information', text: 'Street Address in {Destination}:', type: QuestionType.TEXT },
  { id: 'q5a', section: 'Contact Information', text: 'Street Address Line 2 in {Destination}:', type: QuestionType.TEXT },
  { id: 'q6', section: 'Contact Information', text: 'City: {Destination}', type: QuestionType.TEXT },
  { id: 'q7', section: 'Contact Information', text: 'State / Province for {Destination}:', type: QuestionType.TEXT },
  { id: 'q8', section: 'Contact Information', text: 'Postal / Zip Code for {Destination}:', type: QuestionType.TEXT },
  { id: 'q9a', section: 'Contact Information', text: 'Upload Picture of {Destination} 1:', type: QuestionType.FILE },
  { id: 'q9b', section: 'Contact Information', text: 'Upload Picture of {Destination} 2:', type: QuestionType.FILE },
  { id: 'q9c', section: 'Contact Information', text: 'Upload Picture of {Destination} 3:', type: QuestionType.FILE },
  { id: 'q9d', section: 'Contact Information', text: 'Upload Picture of {Destination} 4:', type: QuestionType.FILE },
  { id: 'q9e', section: 'Contact Information', text: 'Upload Picture of {Destination} 5:', type: QuestionType.FILE },
  { id: 'q10a', section: 'Contact Information', text: 'Brief Description of Sustainable Tourism Services in {Destination}:', type: QuestionType.TEXTAREA },
  { id: 'q11a', section: 'Contact Information', text: 'Website Address for {Destination}:', type: QuestionType.URL },
  // Governance & Planning
  { id: 'q12a', section: 'Governance & Planning', text: 'What is the website for the tourist promotion of {Destination}?', type: QuestionType.URL },
  { id: 'q13a', section: 'Governance & Planning', text: 'How are sustainability concerns communicated to tourism related enterprises in {Destination}?', type: QuestionType.TEXTAREA },
  { id: 'q14a', section: 'Governance & Planning', text: 'Does {Destination} have a plan to monitor and manage visitor movement and activity and increase or reduce them at certain times or locations to better balance the needs of the local economy, community, cultural heritage, and environment?', type: QuestionType.BOOLEAN },
  { id: 'q14b', section: 'Governance & Planning', text: 'Please upload {Destination} plan', type: QuestionType.FILE },
  { id: 'q15a', section: 'Governance & Planning', text: 'Does {Destination} have a risk and crisis management plan appropriate to the community including key elements communicated to visitors, residents, and the business community?', type: QuestionType.BOOLEAN },
  { id: 'q15b', section: 'Governance & Planning', text: 'Describe the risk and crisis management plan.', type: QuestionType.TEXTAREA },
  { id: 'q16b', section: 'Governance & Planning', text: 'Reference Image 1 for this Section (related to {Destination}):', type: QuestionType.FILE },
  { id: 'q16c', section: 'Governance & Planning', text: 'Reference Image 2 for this Section (related to {Destination}):', type: QuestionType.FILE },
  // Stakeholder Engagement
  { id: 'q17a', section: 'Stakeholder Engagement', text: 'Does {Destination} provide guests with the opportunity to rate the value of services received?', type: QuestionType.BOOLEAN },
  { id: 'q17b', section: 'Stakeholder Engagement', text: 'If yes, describe how feedback is collected.', type: QuestionType.TEXTAREA },
  { id: 'q18a', section: 'Stakeholder Engagement', text: 'Does {Destination} provide stakeholders the opportunity to provide feedback on their concerns and satisfaction with sustainable tourism management?', type: QuestionType.BOOLEAN },
  { id: 'q18b', section: 'Stakeholder Engagement', text: 'If yes, describe how feedback is collected.', type: QuestionType.TEXTAREA },
  { id: 'q19a', section: 'Stakeholder Engagement', text: 'Reference Image 1 for this Section (related to {Destination}):', type: QuestionType.FILE },
  { id: 'q19b', section: 'Stakeholder Engagement', text: 'Reference Image 2 for this Section (related to {Destination}):', type: QuestionType.FILE },
  { id: 'q19c', section: 'Stakeholder Engagement', text: 'Reference Image 3 for this Section (related to {Destination}):', type: QuestionType.FILE },
  { id: 'q20a', section: 'Stakeholder Engagement', text: 'Source Link for Stakeholder Engagement Info:', type: QuestionType.URL },
  // Community & Economy
  { id: 'q21a', section: 'Community & Economy', text: 'How many tourism businesses in {Destination} have sustainability plans linked to the Destination or community plan?', type: QuestionType.NUMBER },
  { id: 'q21b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q22a', section: 'Community & Economy', text: 'Reference Image 1 for this Section:', type: QuestionType.FILE },
  { id: 'q22b', section: 'Community & Economy', text: 'Reference Image 2 for this Section:', type: QuestionType.FILE },
  { id: 'q22c', section: 'Community & Economy', text: 'Reference Image 3 for this Section:', type: QuestionType.FILE },
  { id: 'q23a', section: 'Community & Economy', text: 'What is the average number of room nights for guest stays in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q23b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q24a', section: 'Community & Economy', text: 'What is the number of tourists / guests in {Destination} on a peak night?', type: QuestionType.NUMBER },
  { id: 'q24b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q25a', section: 'Community & Economy', text: 'What is the total population of permanent residents in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q25b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q26a', section: 'Community & Economy', text: 'What is the total number of local people employed in tourism in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q26b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q27a', section: 'Community & Economy', text: 'What is the number of men employed in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q27b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q28a', section: 'Community & Economy', text: 'What is the number of women employed in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q28b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q29a', section: 'Community & Economy', text: 'Does {Destination} collect and provide data on how tourism has helped bring new services and infrastructure to the community?', type: QuestionType.BOOLEAN },
  { id: 'q29b', section: 'Community & Economy', text: 'Describe the data collection process.', type: QuestionType.TEXTAREA },
  { id: 'q30a', section: 'Community & Economy', text: 'Please list activities and initiatives in {Destination} to improve the health and well-being of the residents.', type: QuestionType.TEXTAREA },
  { id: 'q30b', section: 'Community & Economy', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q31a', section: 'Community & Economy', text: 'What are the major infrastructure improvements that tourism brought to {Destination}?', type: QuestionType.TEXTAREA },
  { id: 'q32a', section: 'Community & Economy', text: 'Please list the top five major social services in {Destination} attributed to the economic benefits derived from tourism.', type: QuestionType.TEXTAREA },
  // Labor & Human Rights
  { id: 'q33a', section: 'Labor & Human Rights', text: 'Does {Destination} provide opportunities and training in tourism?', type: QuestionType.BOOLEAN },
  { id: 'q34a', section: 'Labor & Human Rights', text: 'What percent of the salaried employees and what percent of the full time hourly employees (at least 32 hrs a week) in {Destination} are paid a living wage?', type: QuestionType.TEXTAREA },
  { id: 'q34b', section: 'Labor & Human Rights', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q35a', section: 'Labor & Human Rights', text: 'Does {Destination} have programs or incentives to encourage the use of local supply chains, purchase of fair trade products, and other sustainable investment?', type: QuestionType.BOOLEAN },
  { id: 'q35b', section: 'Labor & Human Rights', text: 'Describe these programs or incentives.', type: QuestionType.TEXTAREA },
  { id: 'q36a', section: 'Labor & Human Rights', text: 'Does {Destination} have a program to encourage enterprises, visitors, and the public to contribute to its sustainability initiatives?', type: QuestionType.BOOLEAN },
  { id: 'q36b', section: 'Labor & Human Rights', text: 'Describe the program.', type: QuestionType.TEXTAREA },
  { id: 'q37a', section: 'Labor & Human Rights', text: 'Does {Destination} uphold international standards on human rights including laws, practices or code of conduct to prevent and report human trafficking, sexual exploitation, discrimination, and harassment?', type: QuestionType.BOOLEAN },
  { id: 'q37b', section: 'Labor & Human Rights', text: 'Describe laws, practices, and enforcement.', type: QuestionType.TEXTAREA },
  { id: 'q38a', section: 'Labor & Human Rights', text: 'Does {Destination} have laws and regulations regarding property rights to record and document acquisitions and to protect access to key resources, and protect indigenous rights where applicable?', type: QuestionType.BOOLEAN },
  { id: 'q38b', section: 'Labor & Human Rights', text: 'Describe these laws and regulations.', type: QuestionType.TEXTAREA },
  { id: 'q39a', section: 'Labor & Human Rights', text: 'Does {Destination} have a system to monitor, prevent, publicly report, and respond to crime, safety, and health hazards that address the needs of both visitors and residents?', type: QuestionType.BOOLEAN },
  { id: 'q39b', section: 'Labor & Human Rights', text: 'Describe the system.', type: QuestionType.TEXTAREA },
  { id: 'q40a', section: 'Labor & Human Rights', text: 'Does {Destination} when practical provide accessibility to facilities and services, including those of natural and cultural importance, to persons with disabilities and others who have special requirements or other special needs?', type: QuestionType.BOOLEAN },
  { id: 'q40b', section: 'Labor & Human Rights', text: 'Describe accessibility provisions.', type: QuestionType.TEXTAREA },
  { id: 'q41a', section: 'Labor & Human Rights', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q41b', section: 'Labor & Human Rights', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q41c', section: 'Labor & Human Rights', text: 'Reference Image 3:', type: QuestionType.FILE },
  // Economic Performance
  { id: 'q42a', section: 'Economic Performance', text: 'What is the total number of employment for {Destination} outside of tourism?', type: QuestionType.NUMBER },
  { id: 'q42b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q43a', section: 'Economic Performance', text: 'What percent of revenues in {Destination} are generated by tourism?', type: QuestionType.NUMBER },
  { id: 'q43b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q44a', section: 'Economic Performance', text: 'What is the total occupancy level (tourist arrivals) by month in {Destination}?', type: QuestionType.TEXTAREA },
  { id: 'q44b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q45a', section: 'Economic Performance', text: 'What is the average annual tourism occupancy in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q45b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q46a', section: 'Economic Performance', text: 'How many enterprise establishments are there in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q46b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q47a', section: 'Economic Performance', text: 'How many enterprise establishments in {Destination} are open year round?', type: QuestionType.NUMBER },
  { id: 'q47b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q48a', section: 'Economic Performance', text: 'What is the number of full-time, year-round jobs in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q48b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q49a', section: 'Economic Performance', text: 'What is the number of temporary jobs in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q49b', section: 'Economic Performance', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q50a', section: 'Economic Performance', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q50b', section: 'Economic Performance', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q50c', section: 'Economic Performance', text: 'Reference Image 3:', type: QuestionType.FILE },
  // Cultural Heritage
  { id: 'q51a', section: 'Cultural Heritage', text: 'Does {Destination} have a policy and system to evaluate, rehabilitate, and conserve cultural assets including both built heritage and landscapes?', type: QuestionType.BOOLEAN },
  { id: 'q51b', section: 'Cultural Heritage', text: 'Describe the policy and system.', type: QuestionType.TEXTAREA },
  { id: 'q52a', section: 'Cultural Heritage', text: 'Does {Destination} have laws that govern the proper sale, trade, display, or gifting of historical and archaeological artifacts and are such laws enforced and publicly communicated to business and visitors?', type: QuestionType.BOOLEAN },
  { id: 'q52b', section: 'Cultural Heritage', text: 'Describe the laws and enforcement.', type: QuestionType.TEXTAREA },
  { id: 'q53a', section: 'Cultural Heritage', text: 'Does {Destination} support the celebration and protection of intangible cultural heritage including but not limited to art, music, language, gastronomy, and other aspects that give the community a unique sense of place?', type: QuestionType.BOOLEAN },
  { id: 'q53b', section: 'Cultural Heritage', text: 'Describe the support provided.', type: QuestionType.TEXTAREA },
  { id: 'q54a', section: 'Cultural Heritage', text: 'Does {Destination} monitor, protect, and when necessary rehabilitate or restore local community access to natural and cultural sites?', type: QuestionType.BOOLEAN },
  { id: 'q54b', section: 'Cultural Heritage', text: 'Describe the monitoring and protection system.', type: QuestionType.TEXTAREA },
  { id: 'q55a', section: 'Cultural Heritage', text: 'Are the information provided to inform visitors in {Destination} culturally appropriate, developed with community collaboration, and communicated in languages pertinent to visitors and residents?', type: QuestionType.BOOLEAN },
  { id: 'q55b', section: 'Cultural Heritage', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q55c', section: 'Cultural Heritage', text: 'Please upload sample information and/or insert URL link.', type: QuestionType.FILE },
  { id: 'q56a', section: 'Cultural Heritage', text: 'Does {Destination} have a system to contribute to the protection and preservation of intellectual property rights of communities and individuals?', type: QuestionType.BOOLEAN },
  { id: 'q56b', section: 'Cultural Heritage', text: 'Describe the system.', type: QuestionType.TEXTAREA },
  { id: 'q57a', section: 'Cultural Heritage', text: 'Does {Destination} have a system for the management of visitors within and around cultural sites, which takes account of their characteristics, capacity and sensitivity, and seeks to optimize visitor flow and minimize adverse impacts?', type: QuestionType.BOOLEAN },
  { id: 'q57b', section: 'Cultural Heritage', text: 'Describe the visitor management system.', type: QuestionType.TEXTAREA },
  { id: 'q58a', section: 'Cultural Heritage', text: 'Does {Destination} provide accurate material to inform visitors of the significance of the cultural and natural aspects of the sites they visit?', type: QuestionType.BOOLEAN },
  { id: 'q58b', section: 'Cultural Heritage', text: 'Describe the materials provided.', type: QuestionType.TEXTAREA },
  { id: 'q59a', section: 'Cultural Heritage', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q59b', section: 'Cultural Heritage', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q59c', section: 'Cultural Heritage', text: 'Reference Image 3:', type: QuestionType.FILE },
  // Energy Management
  { id: 'q60a', section: 'Energy Management', text: 'What is the total energy consumption in kilowatt hours (kWh) from all sources in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q60b', section: 'Energy Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q61a', section: 'Energy Management', text: 'How much energy in kWh is generated from renewable resources in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q61b', section: 'Energy Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q62a', section: 'Energy Management', text: 'What is the total annual amount of GHG emissions generated in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q62b', section: 'Energy Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q63a', section: 'Energy Management', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q63b', section: 'Energy Management', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q63c', section: 'Energy Management', text: 'Reference Image 3:', type: QuestionType.FILE },
  // Water Management
  { id: 'q64a', section: 'Water Management', text: 'What is the annual volume of freshwater consumed in liters in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q64b', section: 'Water Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q65a', section: 'Water Management', text: 'What percentage of freshwater is reclaimed annually in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q65b', section: 'Water Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q66a', section: 'Water Management', text: 'What is the percentage of tourism establishments in {Destination} with water treated to international potable standards?', type: QuestionType.NUMBER },
  { id: 'q66b', section: 'Water Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q67a', section: 'Water Management', text: 'Does {Destination} monitor water quality for drinking, recreational, and ecological purposes and have a system to respond to any water quality issues in a timely manner?', type: QuestionType.BOOLEAN },
  { id: 'q67b', section: 'Water Management', text: 'Describe the monitoring system.', type: QuestionType.TEXTAREA },
  { id: 'q68a', section: 'Water Management', text: 'What is the frequency of water-borne diseases: number/percentage of visitors reporting water-borne illnesses during their stay in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q68b', section: 'Water Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q69a', section: 'Water Management', text: 'What is the daily average water use per person per day in liters in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q69b', section: 'Water Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q70a', section: 'Water Management', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q70b', section: 'Water Management', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q70c', section: 'Water Management', text: 'Reference Image 3:', type: QuestionType.FILE },
  // Waste & Wastewater Management
  { id: 'q71a', section: 'Waste & Wastewater Management', text: 'What is the percentage of sewage from {Destination} receiving treatment (to primary, secondary, tertiary levels)?', type: QuestionType.NUMBER },
  { id: 'q71b', section: 'Waste & Wastewater Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q72a', section: 'Waste & Wastewater Management', text: 'What is the percentage of tourism accommodations in {Destination} using sewage treatment systems?', type: QuestionType.NUMBER },
  { id: 'q72b', section: 'Waste & Wastewater Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q73a', section: 'Waste & Wastewater Management', text: 'What is the volume of waste produced by {Destination} (tonnes) annually?', type: QuestionType.NUMBER },
  { id: 'q73b', section: 'Waste & Wastewater Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q74a', section: 'Waste & Wastewater Management', text: 'What is the volume of waste recycled in {Destination} (tonnes) per year?', type: QuestionType.NUMBER },
  { id: 'q74b', section: 'Waste & Wastewater Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q75a', section: 'Waste & Wastewater Management', text: 'What is the volume of waste sent to landfill in {Destination} (tonnes) per year?', type: QuestionType.NUMBER },
  { id: 'q75b', section: 'Waste & Wastewater Management', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q76a', section: 'Waste & Wastewater Management', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q76b', section: 'Waste & Wastewater Management', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q76c', section: 'Waste & Wastewater Management', text: 'Reference Image 3:', type: QuestionType.FILE },
  // ... continue with all other questions
  { id: 'q77a', section: 'Land Use & Biodiversity', text: 'Does {Destination} have a land use or development planning process, including tourism, and provisions for monitoring the plan’s implementation?', type: QuestionType.BOOLEAN },
  { id: 'q78a', section: 'Land Use & Biodiversity', text: 'What is the percentage of area in {Destination} subject to control (density, design, etc.)?', type: QuestionType.NUMBER },
  { id: 'q78b', section: 'Land Use & Biodiversity', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q79a', section: 'Land Use & Biodiversity', text: 'What percent of land area in {Destination} is set aside for biodiversity conservation?', type: QuestionType.NUMBER },
  { id: 'q79b', section: 'Land Use & Biodiversity', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q80a', section: 'Land Use & Biodiversity', text: 'Are there plans in place in {Destination} to protect biodiversity and monitor their effectiveness?', type: QuestionType.BOOLEAN },
  { id: 'q80b', section: 'Land Use & Biodiversity', text: 'Describe the plans.', type: QuestionType.TEXTAREA },
  { id: 'q81a', section: 'Land Use & Biodiversity', text: 'Does {Destination} have a system for the management of visitors within and around natural sites, which takes account of their characteristics, capacity and sensitivity, and seeks to optimize visitor flow and minimize adverse impacts?', type: QuestionType.BOOLEAN },
  { id: 'q81b', section: 'Land Use & Biodiversity', text: 'Describe the system.', type: QuestionType.TEXTAREA },
  { id: 'q82a', section: 'Land Use & Biodiversity', text: 'Does {Destination} have a system to ensure compliance with local, national, and international laws and standards for wildlife interaction and to ensure animal welfare and conservation of animal species?', type: QuestionType.BOOLEAN },
  { id: 'q82b', section: 'Land Use & Biodiversity', text: 'Describe the system.', type: QuestionType.TEXTAREA },
  { id: 'q83a', section: 'Land Use & Biodiversity', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q83b', section: 'Land Use & Biodiversity', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q83c', section: 'Land Use & Biodiversity', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q84a', section: 'Sustainable Construction', text: 'Is an environmental impact assessment required before new construction in {Destination}?', type: QuestionType.BOOLEAN },
  { id: 'q84b', section: 'Sustainable Construction', text: 'Describe the requirements.', type: QuestionType.TEXTAREA },
  { id: 'q85a', section: 'Sustainable Construction', text: 'Are there energy efficiency standards for new construction or redevelopment in {Destination}?', type: QuestionType.BOOLEAN },
  { id: 'q85b', section: 'Sustainable Construction', text: 'Describe the standards.', type: QuestionType.TEXTAREA },
  { id: 'q86a', section: 'Sustainable Construction', text: 'Are there disaster reduction standards for new construction or redevelopment in {Destination} (hurricane, floodplain, tornado, earthquake, etc.)?', type: QuestionType.BOOLEAN },
  { id: 'q86b', section: 'Sustainable Construction', text: 'Describe the standards.', type: QuestionType.TEXTAREA },
  { id: 'q87a', section: 'Sustainable Construction', text: 'Does {Destination} have guidelines and regulations to minimize light and noise pollution?', type: QuestionType.BOOLEAN },
  { id: 'q87b', section: 'Sustainable Construction', text: 'Describe the guidelines.', type: QuestionType.TEXTAREA },
  { id: 'q88a', section: 'Sustainable Construction', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q88b', section: 'Sustainable Construction', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q88c', section: 'Sustainable Construction', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q89a', section: 'Transportation', text: 'What is the total number of people who use mass transit each year in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q89b', section: 'Transportation', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q90a', section: 'Transportation', text: 'How many kilometers of dedicated bike trails are in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q90b', section: 'Transportation', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q91a', section: 'Transportation', text: 'How many kilometers of designated bike lanes are in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q91b', section: 'Transportation', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q92a', section: 'Transportation', text: 'How many kilometers of pedestrian trails are in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q92b', section: 'Transportation', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q93a', section: 'Transportation', text: 'What is the number of vehicles owned and operated within {Destination}?', type: QuestionType.NUMBER },
  { id: 'q93b', section: 'Transportation', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q94a', section: 'Transportation', text: 'What is the number of hybrid, electric, or energy efficient vehicles owned and operated in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q94b', section: 'Transportation', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q95a', section: 'Transportation', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q95b', section: 'Transportation', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q95c', section: 'Transportation', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q96a', section: 'Waste Reduction (Plastics)', text: 'How many tourist businesses in {Destination} refrain from using single-use plastic bags?', type: QuestionType.NUMBER },
  { id: 'q96b', section: 'Waste Reduction (Plastics)', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q97a', section: 'Waste Reduction (Plastics)', text: 'How many tourist businesses in {Destination} refrain from using plastic straws?', type: QuestionType.NUMBER },
  { id: 'q97b', section: 'Waste Reduction (Plastics)', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q98a', section: 'Waste Reduction (Plastics)', text: 'How many tourist businesses in {Destination} refrain from using plastic lids?', type: QuestionType.NUMBER },
  { id: 'q98b', section: 'Waste Reduction (Plastics)', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q99a', section: 'Waste Reduction (Plastics)', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q99b', section: 'Waste Reduction (Plastics)', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q99c', section: 'Waste Reduction (Plastics)', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q100a', section: 'Local Food Sourcing', text: 'Does {Destination} participate in programs to source food locally?', type: QuestionType.BOOLEAN },
  { id: 'q100b', section: 'Local Food Sourcing', text: 'Describe the programs.', type: QuestionType.TEXTAREA },
  { id: 'q101a', section: 'Local Food Sourcing', text: 'Does {Destination} participate in programs to compost food waste?', type: QuestionType.BOOLEAN },
  { id: 'q101b', section: 'Local Food Sourcing', text: 'Describe the programs.', type: QuestionType.TEXTAREA },
  { id: 'q102a', section: 'Local Food Sourcing', text: 'Are there farmers markets or local food cooperatives in {Destination} that serve as a resource for the community?', type: QuestionType.BOOLEAN },
  { id: 'q102b', section: 'Local Food Sourcing', text: 'Describe them.', type: QuestionType.TEXTAREA },
  { id: 'q103a', section: 'Local Food Sourcing', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q103b', section: 'Local Food Sourcing', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q103c', section: 'Local Food Sourcing', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q104a', section: 'Seafood Sourcing', text: 'Is seafood caught locally in {Destination}?', type: QuestionType.BOOLEAN },
  { id: 'q104b', section: 'Seafood Sourcing', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q105a', section: 'Seafood Sourcing', text: 'What percent of seafood sold in restaurants and stores in {Destination} is caught locally?', type: QuestionType.NUMBER },
  { id: 'q105b', section: 'Seafood Sourcing', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q106a', section: 'Seafood Sourcing', text: 'Do restaurants in {Destination} advertise and offer seafood that is caught locally?', type: QuestionType.BOOLEAN },
  { id: 'q106b', section: 'Seafood Sourcing', text: 'Describe how.', type: QuestionType.TEXTAREA },
  { id: 'q107a', section: 'Seafood Sourcing', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q107b', section: 'Seafood Sourcing', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q107c', section: 'Seafood Sourcing', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q108a', section: 'Habitat & Species Protection', text: 'Please provide a description of current habitat protection/restoration/enhancement programs in {Destination}.', type: QuestionType.TEXTAREA },
  { id: 'q109a', section: 'Habitat & Species Protection', text: 'Does {Destination} have a program to protect threatened and endangered species?', type: QuestionType.BOOLEAN },
  { id: 'q109b', section: 'Habitat & Species Protection', text: 'Describe the program.', type: QuestionType.TEXTAREA },
  { id: 'q110a', section: 'Habitat & Species Protection', text: 'What percentage of land within {Destination} is dedicated to parks and/or open space?', type: QuestionType.NUMBER },
  { id: 'q110b', section: 'Habitat & Species Protection', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q111a', section: 'Habitat & Species Protection', text: 'Does {Destination} participate in any tree planting or reforestation programs?', type: QuestionType.BOOLEAN },
  { id: 'q111b', section: 'Habitat & Species Protection', text: 'Describe the programs.', type: QuestionType.TEXTAREA },
  { id: 'q112a', section: 'Habitat & Species Protection', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q112b', section: 'Habitat & Species Protection', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q112c', section: 'Habitat & Species Protection', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q113a', section: 'Marinas', text: 'How many marinas are in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q113b', section: 'Marinas', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q114a', section: 'Marinas', text: 'How many marinas in {Destination} are certified as Clean Marinas?', type: QuestionType.NUMBER },
  { id: 'q114b', section: 'Marinas', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q115a', section: 'Marinas', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q115b', section: 'Marinas', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q115c', section: 'Marinas', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q116a', section: 'Education & Awareness', text: 'What is the annual number of people reached through environmental or sustainability education programs in {Destination}?', type: QuestionType.NUMBER },
  { id: 'q116b', section: 'Education & Awareness', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q117a', section: 'Education & Awareness', text: 'List the top four groups or organizations in {Destination} providing sustainability education.', type: QuestionType.TEXTAREA },
  { id: 'q117b', section: 'Education & Awareness', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q118a', section: 'Education & Awareness', text: 'Reference Image 1:', type: QuestionType.FILE },
  { id: 'q118b', section: 'Education & Awareness', text: 'Reference Image 2:', type: QuestionType.FILE },
  { id: 'q118c', section: 'Education & Awareness', text: 'Reference Image 3:', type: QuestionType.FILE },
  { id: 'q119a', section: 'Climate & Air Quality', text: 'Do any policies and/or programs exist in {Destination} to become a net zero carbon community?', type: QuestionType.BOOLEAN },
  { id: 'q119b', section: 'Climate & Air Quality', text: 'Describe the policies/programs.', type: QuestionType.TEXTAREA },
  { id: 'q120a', section: 'Climate & Air Quality', text: 'Are there any policies and/or programs in {Destination} designed to encourage mass transportation for all guest activities once they arrive?', type: QuestionType.BOOLEAN },
  { id: 'q120b', section: 'Climate & Air Quality', text: 'Describe the policies/programs.', type: QuestionType.TEXTAREA },
  { id: 'q121a', section: 'Climate & Air Quality', text: 'Does {Destination} offer any carbon offsets for all travel of guests once they reach the community?', type: QuestionType.BOOLEAN },
  { id: 'q121b', section: 'Climate & Air Quality', text: 'Describe the carbon offsets.', type: QuestionType.TEXTAREA },
  { id: 'q122a', section: 'Climate & Air Quality', text: 'Does {Destination} offer any carbon offsets for guest activities that require the use of non-resort transportation?', type: QuestionType.BOOLEAN },
  { id: 'q122b', section: 'Climate & Air Quality', text: 'Describe the carbon offsets.', type: QuestionType.TEXTAREA },
  { id: 'q123a', section: 'Climate & Air Quality', text: 'Does {Destination} have a policy and/or program to not use ozone-depleting substances?', type: QuestionType.BOOLEAN },
  { id: 'q123b', section: 'Climate & Air Quality', text: 'Upload policy/program document.', type: QuestionType.FILE },
  { id: 'q124a', section: 'Climate & Air Quality', text: 'Does {Destination} have a policy and/or program in place to reduce air pollution and/or improve air quality?', type: QuestionType.BOOLEAN },
  { id: 'q124b', section: 'Climate & Air Quality', text: 'Upload policy/program document.', type: QuestionType.FILE },
  { id: 'q125a', section: 'Climate & Air Quality', text: 'What is the yearly average Air Quality Index (AQI) of {Destination}?', type: QuestionType.NUMBER },
  { id: 'q125b', section: 'Climate & Air Quality', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q126a', section: 'Climate & Air Quality', text: 'What are the yearly highs and lows for Air Quality Index (AQI) in {Destination}?', type: QuestionType.TEXT },
  { id: 'q126b', section: 'Climate & Air Quality', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q127a', section: 'Environmental Protection', text: 'Does {Destination} have a policy and/or program in place to protect and enhance ecosystems for biodiversity?', type: QuestionType.BOOLEAN },
  { id: 'q127b', section: 'Environmental Protection', text: 'Describe the policy/program.', type: QuestionType.TEXTAREA },
  { id: 'q127c', section: 'Environmental Protection', text: 'Upload policy document.', type: QuestionType.FILE },
  { id: 'q128a', section: 'Environmental Protection', text: 'Does {Destination} have a policy and/or program in place to reduce or not use any toxic chemicals?', type: QuestionType.BOOLEAN },
  { id: 'q128b', section: 'Environmental Protection', text: 'Upload policy document.', type: QuestionType.FILE },
  { id: 'q129a', section: 'Environmental Protection', text: 'Does {Destination} have a policy and/or program in place to not deplete aquifer levels or endanger community fresh water supplies?', type: QuestionType.BOOLEAN },
  { id: 'q129b', section: 'Environmental Protection', text: 'Describe the policy/program.', type: QuestionType.TEXTAREA },
  { id: 'q129c', section: 'Environmental Protection', text: 'Upload policy document.', type: QuestionType.FILE },
  { id: 'q130a', section: 'Environmental Protection', text: 'Does {Destination} have a policy and/or program in place to prevent tree loss and encourage the planting of native trees when practical?', type: QuestionType.BOOLEAN },
  { id: 'q130b', section: 'Environmental Protection', text: 'Describe the policy/program.', type: QuestionType.TEXTAREA },
  { id: 'q130c', section: 'Environmental Protection', text: 'Upload policy document.', type: QuestionType.FILE },
  { id: 'q131a', section: 'Environmental Protection', text: 'Does {Destination} have a program in place to reduce fertilizers that contain phosphates or nitrates?', type: QuestionType.BOOLEAN },
  { id: 'q131b', section: 'Environmental Protection', text: 'Describe the program.', type: QuestionType.TEXTAREA },
  { id: 'q131c', section: 'Environmental Protection', text: 'Upload policy document.', type: QuestionType.FILE },
  { id: 'q132a', section: 'Environmental Protection', text: 'Are there plans in place in {Destination} to protect threatened or endangered species?', type: QuestionType.BOOLEAN },
  { id: 'q132b', section: 'Environmental Protection', text: 'Describe the plans.', type: QuestionType.TEXTAREA },
  { id: 'q133a', section: 'Success Story', text: 'What is {Destination}’s best sustainable tourism success story to date?', type: QuestionType.TEXTAREA },
  { id: 'q133b', section: 'Success Story', text: 'Source Link:', type: QuestionType.URL },
  { id: 'q134a', section: 'Success Story', text: 'Reference Image 1 for success story:', type: QuestionType.FILE },
  { id: 'q134b', section: 'Success Story', text: 'Reference Image 2 for success story:', type: QuestionType.FILE },
  { id: 'q134c', section: 'Success Story', text: 'Reference Image 3 for success story:', type: QuestionType.FILE },
];

export const questions: Question[] = [...baseQuestions, ...hawaiiQuestions];
